apiVersion: v1
kind: Pod
metadata:
  name: deployment-pvc-mount-pod
  namespace: budget-app-production
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: shared-storage
          mountPath: /mnt/data
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
  volumes:
    - name: shared-storage
      persistentVolumeClaim:
        claimName: deployment-shared-pvc
