apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deployment-shared-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: crc-csi-hostpath-provisioner
