apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-deployment-pipeline-budget-app-backend
spec:
  pipelineRef:
    name: deployment-pipeline
  params:
    - name: repo-url
      value: https://github.com/aimemalaika/budget-app-backend
    - name: branch
      value: main
    - name: image-name
      value: image-registry.openshift-image-registry.svc:5000/budget-app-production/budget-app-backend:latest
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: deployment-shared-pvc  # Same PVC for both pipelines
      subPath: budget-app-backend  # Mount the backend pipeline at a specific path
