apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deployment-pipeline
spec:
  params:
    - name: repo-url
      type: string
      description: The URL of the Git repository
    - name: branch
      type: string
      description: The branch to checkout
      default: "main"
    - name: image-name
      type: string
      description: Image name to build and push
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: "$(params.repo-url)"
        - name: revision
          value: "$(params.branch)"
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: build-image
      runAfter: ["clone-repo"]
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: "$(params.image-name)"
        - name: DOCKERFILE
          value: "./Dockerfile"
        - name: CONTEXT
          value: "$(workspaces.source.path)"
      workspaces:
        - name: source
          workspace: shared-workspace
