apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-app-backend-deployment
  namespace: budget-app-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  budget-app-backend
  template:
    metadata:
      labels:
        app:  budget-app-backend
    spec:
      containers:
        - name:  budget-app-backend
          image: image-registry.openshift-image-registry.svc:5000/budget-app-production/budget-app-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: 8080
