apiVersion: v1
kind: Service
metadata:
  name: budget-app-backend-service
  namespace: budget-app-production
spec:
  selector:
    app:  budget-app-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
