apiVersion: v1
kind: Service
metadata:
  name: budget-app-backend-service-gitops
  namespace: budget-app-gitops-setup
spec:
  selector:
    app:  budget-app-backend-gitops
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP