apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-app-deployment
  namespace: budge-app-with-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-app
  template:
    metadata:
      labels:
        app: budget-app
    spec:
      containers:
        - name: budget-app
          image: image-registry.openshift-image-registry.svc:5000/budge-app-with-production/budget-app-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
            - name: NEXT_PUBLIC_API_BASE_URL
              value: https://api.example.com
