apiVersion: v1
kind: Secret
metadata:
  name: git-basic-auth
type: Opaque
stringData:
  .git-credentials: https://<USERNAME>:<GITHUB_TOKEN>@github.com
  .gitconfig: |
    [credential]
      helper = store
